"""Add Act model and update relationships

Revision ID: 059617f91179
Revises: b2d3e4f5g6h7
Create Date: 2025-04-10 07:39:39.096059

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '059617f91179'
down_revision: Union[str, None] = 'b2d3e4f5g6h7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='actstatus'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'slug', name='uix_game_act_slug')
    )
    op.create_index(op.f('ix_acts_slug'), 'acts', ['slug'], unique=False)
    op.create_unique_constraint(None, 'event_sources', ['name'])
    op.add_column('scenes', sa.Column('act_id', sa.String(), nullable=False))
    op.drop_constraint('uix_game_scene_slug', 'scenes', type_='unique')
    op.create_unique_constraint('uix_act_scene_slug', 'scenes', ['act_id', 'slug'])
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.create_foreign_key(None, 'scenes', 'acts', ['act_id'], ['id'])
    op.drop_column('scenes', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('game_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.create_foreign_key(None, 'scenes', 'games', ['game_id'], ['id'])
    op.drop_constraint('uix_act_scene_slug', 'scenes', type_='unique')
    op.create_unique_constraint('uix_game_scene_slug', 'scenes', ['game_id', 'slug'])
    op.drop_column('scenes', 'act_id')
    op.drop_constraint(None, 'event_sources', type_='unique')
    op.drop_index(op.f('ix_acts_slug'), table_name='acts')
    op.drop_table('acts')
    # ### end Alembic commands ###
