"""Update Event model to not have a direct relationship to the Game model.

Revision ID: 0a5d38e68a85
Revises: 059617f91179
Create Date: 2025-04-11 15:40:52.153242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5d38e68a85'
down_revision: Union[str, None] = '059617f91179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('game_id', sa.VARCHAR(length=255), nullable=False))
    op.create_foreign_key(None, 'events', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
