"""Add ondelete=CASCADE to foreign keys

Revision ID: eef7a1859ae9
Revises: 0001
Create Date: 2025-05-02 06:54:55.169808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef7a1859ae9'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_new')
    op.drop_constraint(None, 'acts', type_='foreignkey')
    op.create_foreign_key(None, 'acts', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dice_rolls', type_='foreignkey')
    op.create_foreign_key(None, 'dice_rolls', 'scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interpretation_sets', type_='foreignkey')
    op.create_foreign_key(None, 'interpretation_sets', 'scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interpretations', type_='foreignkey')
    op.create_foreign_key(None, 'interpretations', 'interpretation_sets', ['set_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_scenes_is_active'), 'scenes', ['is_active'], unique=False)
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.create_foreign_key(None, 'scenes', 'acts', ['act_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scenes', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('status', sa.VARCHAR(length=9), nullable=False))
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.create_foreign_key(None, 'scenes', 'acts', ['act_id'], ['id'])
    op.drop_index(op.f('ix_scenes_is_active'), table_name='scenes')
    op.drop_constraint(None, 'interpretations', type_='foreignkey')
    op.create_foreign_key(None, 'interpretations', 'interpretation_sets', ['set_id'], ['id'])
    op.drop_constraint(None, 'interpretation_sets', type_='foreignkey')
    op.create_foreign_key(None, 'interpretation_sets', 'scenes', ['scene_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'scenes', ['scene_id'], ['id'])
    op.drop_constraint(None, 'dice_rolls', type_='foreignkey')
    op.create_foreign_key(None, 'dice_rolls', 'scenes', ['scene_id'], ['id'])
    op.drop_constraint(None, 'acts', type_='foreignkey')
    op.create_foreign_key(None, 'acts', 'games', ['game_id'], ['id'])
    op.create_table('events_new',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('scene_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('game_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('interpretation_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('modified_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['interpretation_id'], ['interpretations.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['event_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
